import * as Print from 'expo-print';
import { format } from 'date-fns';
import { Order } from '@/types';

function escapeHtml(s: string | undefined | null): string {
  if (!s) return '';
  return s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c] as string));
}

function buildOrderHtml(order: Order): string {
  const rows = (order.items ?? [])
    .map(
      (it, idx) => `
      <tr>
        <td>${idx + 1}</td>
        <td>${escapeHtml(it.productName)}${it.strength ? ` (${escapeHtml(it.strength)})` : ''}</td>
        <td>${escapeHtml(it.packing)}</td>
        <td style="text-align:center">${it.quantity}</td>
        <td style="text-align:center">${it.freeQuantity || '-'}</td>
      </tr>`
    )
    .join('');

  return `
  <html>
    <head>
      <meta charset="utf-8" />
      <style>
        body { font-family: -apple-system, Roboto, Arial, sans-serif; color: #1A2233; padding: 24px; }
        h1 { color: #0D5BBD; font-size: 20px; margin-bottom: 4px; }
        .meta { font-size: 12px; color: #555; margin-bottom: 16px; }
        table { width: 100%; border-collapse: collapse; margin-top: 12px; }
        th, td { border: 1px solid #C7D3E6; padding: 6px 8px; font-size: 13px; }
        th { background: #EEF3FB; text-align: left; }
        .totals { margin-top: 14px; font-size: 14px; font-weight: bold; text-align: right; }
        .remarks { margin-top: 14px; font-size: 13px; }
        .footer { margin-top: 30px; font-size: 11px; color: #888; text-align: center; }
      </style>
    </head>
    <body>
      <h1>Pharma Order Book</h1>
      <div class="meta">
        <div><b>Customer:</b> ${escapeHtml(order.customerName)} ${order.shopName ? `(${escapeHtml(order.shopName)})` : ''}</div>
        <div><b>Order Date:</b> ${format(order.orderDate, 'dd MMM yyyy')}</div>
      </div>
      <table>
        <thead>
          <tr><th>#</th><th>Product</th><th>Packing</th><th>Qty</th><th>Free</th></tr>
        </thead>
        <tbody>${rows}</tbody>
      </table>
      <div class="totals">Total Items: ${order.totalItems}</div>
      ${order.remarks ? `<div class="remarks"><b>Remarks:</b> ${escapeHtml(order.remarks)}</div>` : ''}
      <div class="footer">Generated by Pharma Order Book</div>
    </body>
  </html>`;
}

/** Generates a PDF for the order and returns the local file URI. */
export async function generateOrderPdf(order: Order): Promise<string> {
  const html = buildOrderHtml(order);
  const { uri } = await Print.printToFileAsync({ html });
  return uri;
}

/** Opens the native print dialog (also used as a "print-friendly view"). */
export async function printOrder(order: Order): Promise<void> {
  const html = buildOrderHtml(order);
  await Print.printAsync({ html });
}
